spring:
  application:
    name: payment-demo
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lrh,903.520hhhh
    url: jdbc:mysql://localhost:3306/payment-demo?serverTime=GMT%2B8&characterEncoding=utf-8
server:
  port: 8090
mybatis-plus:
  mapper-locations: classpath:xml/**.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# 微信支付相关参数
# 商户号
wxpay:
  mch-id: 1558950191
  # 商户API证书序列号
  mch-serial-no: 34345964330B66427E0D3D28826C4993C77E631F
  # 商户证书文件
  cert-path: apiclient_cert.pem
  # 商户私钥文件
  private-key-path: apiclient_key.pem
  # APIv3密钥
  api-v3-key: UDuLFDcmy5Eb6o0nTNZdu6ek4DDh4K8B
  # APPID
  appid: wx74862e0dfcf69954
  # 微信服务器地址
  domain: https://api.mch.weixin.qq.com
  # 接收结果通知地址
  notify-domain: https://c388-183-230-12-210.ngrok-free.app/
